### ISSUE TITLE
Commands Missing Required Arguments

### ISSUE THREAD

**Issue by kevinmstephens** [CircleCI-Public/config-preview-sdk#109]
Hi, I'm trying to update my config to use commands. However I am getting an error:

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'commit'
# Error calling job: 'deploy-graphql-gateway'
# Error calling command: 'deploy-to-ecr'
# Missing required argument(s): foo
false
```

Relevant parts of the config.

```
version: 2.1
aliases:
  - &base-image
      - image: circleci/node:8
  - &run-install-awscli
      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            /home/circleci/.local/bin/pip install awscli --upgrade --user
  - &run-aws-ecr-login
      - run:
          name: AWS ECR Login
          command: |
            eval $(/home/circleci/.local/bin/aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  - &docker-image_working-dir_resource-class
    docker: *base-image
    working_directory: ~/repo
    resource_class: xlarge
commands:
  deploy-to-ecr:
    description: "Deploys image to ecr."
    parameters:
      foo:
        type: string
    steps:
      - restore_cache: *restore-cache
      - setup_remote_docker:
          docker_layer_caching: true
      - <<: *run-install-awscli
      - <<: *run-aws-ecr-login
      - run: deploy-scripts/build.sh -p=<< parameters.foo >> -t=$CIRCLE_SHA1
jobs:
  deploy-graphql-gateway:
    <<: *docker-image_working-dir_resource-class
    steps:
      - deploy-to-ecr:
        foo: graphql-gateway
  deploy-app-shop:
    <<: *docker-image_working-dir_resource-class
    steps:
      - deploy-to-ecr:
        foo: app-shop
  deploy-legacy-shop-api:
    <<: *docker-image_working-dir_resource-class
    steps:
      - deploy-to-ecr:
        foo: legacy-shop-api
```
