### ISSUE TITLE
How can I pass an integer parameter like "parallelism"?

### ISSUE THREAD

**Issue by bahmutov** [CircleCI-Public/config-preview-sdk#121]
Hi,

We are trying to write a Cypress E2E orb to let the users run end-to-end tests in parallel. Everything is great, users already can load balance across 10 machines as simply as (without orb, simplified version)

```yaml
parallelism: 10
steps:
  - run: npx cypress run --parallel
```

Now in the orb we can pass `parallel` as a parameter, but how can we pass `parallelism` to the executor? I tried passing a string, etc but all attempts are breaking the yml validation schema (`circleci config validate .circleci/config.yml`). I have tried things like this that _pass_ validation

```yaml
parameters:
  parallelism:
    type: string
    default: "1"
parallelism: <<parameters.parallelism>>

- cypress/e2e:
    parallelism: "2"
```

but then the workflow https://circleci.com/workflow-run/b5a654d5-e679-4aed-be56-200f1d977236 simply hangs without starting this job (the workflow is running)

<img width="484" alt="screen shot 2018-10-23 at 12 45 24 pm" src="https://user-images.githubusercontent.com/2212006/47355397-8ef12280-d6c1-11e8-950a-82a79cd45ad6.png">

## desired

 I would love for orb users to simply do:

```yaml
jobs:
  - cypress/e2e:
      parallel: true
      parallelism: 10
```

Or even better would be to do a ternary on a parameter, something like 

```yaml
jobs:
  - cypress/e2e:
      parallel: 10
```

```
parallelism: <<if parameters.parallel > 1>> <<parameters.parallel>> <<else>> 1<<endif>>
```

Something like that. But that is optional, the only real urgent question for us is how to pass `parallelization` as a parameter

Cheers
