### ISSUE TITLE
conditional steps in commands

### ISSUE THREAD

**Issue by bahmutov** [CircleCI-Public/config-preview-sdk#123]
Hi,

Can conditions be used inside commands (and not just jobs)? It seems the only way to do `when / unless` in commands is to use shell scripting like

```
commands: 
  foo
    steps:
      - run:
          name: Check Environment Variables
          command: |
            if [[ -z "${DOCKER_LOGIN}" ]]; then
              echo "DOCKER_LOGIN is not set, will not be able to push image."
              exit 1
            fi
```
which I don't want to do - I want to process user config file and create output that has steps only that are determined by the parameters, something like

```
commands:
  parameters:
    build: 
       type: boolean
  foo:
    steps:
      - conditional:
         when: <<parameters.build>>
         run: npm run build
```
