### ISSUE TITLE
How to do conditionals based on enum?

### ISSUE THREAD

**Issue by bahmutov** [CircleCI-Public/config-preview-sdk#128]
I cannot get a handle or find documentation how to do conditional steps in a job. For example, if I want to perform only one of the 3 commands based on the value of an enum parameter how do I pick the command step.

My config example

```yaml
version: 2.1
jobs:
  example:
    docker:
      - image: node/node:10
    parameters:
      foo:
        description: Foo enum
        type: 'enum'
        enum: ['a', 'b', 'c']
        default: 'a'
    steps:
      - when:
          condition:
            equals: ['<< parameters.foo >>', 'a']
          steps:
            - run: echo 'foo is a'
      - when:
          condition:
            equals: ['<< parameters.foo >>', 'b']
          steps:
            - run: echo 'foo is b'
      - when:
          condition:
            equals: ['<< parameters.foo >>', 'c']
          steps:
            - run: echo 'foo is c'

workflows:
  build:
    jobs:
      - example:
          foo: 'b'
```

I am using `when ... equals` syntax because of the pull request https://github.com/CircleCI-Public/config-preview-sdk/pull/15 which is the closest documentation I could get for showing conditionals with equality

but the effective config from the just runs all the steps

```
$ circleci config process example.yml | sed /^#/d
version: 2
jobs:
  example:
    docker:
    - image: node/node:10
    steps:
    - run:
        command: echo 'foo is a'
    - run:
        command: echo 'foo is b'
    - run:
        command: echo 'foo is c'
workflows:
  build:
    jobs:
    - example
  version: 2
```

Am I using the conditional based on `enum` parameter incorrectly? Is there an orb with such logic?

**Comment by bahmutov** [comment]
fair point @ndintenfass - it was from PR documentation. Yet, the `circleci config process` command does not complain and happily ignores the bad options. But I can do bash shell workaround for now

**Comment by bahmutov** [comment]
ughh, I can do shell commands, but this does not work, because I also need to cache different folders depending on the parameter, and bash shell would not work inside - something like this where I need to modify `paths` list. 
```
- save_cache:
    key: cache-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ~/.npm
      - ~/.cache
```
