### ISSUE TITLE
Do you have any thought about supporting string-array in parameters?

### ISSUE THREAD

**Issue by jmatsu** [CircleCI-Public/config-preview-sdk#131]
Sometimes I wanted to use string-array during orb development.
For example, it's when calling the builtin `save_cache` command.

```
commands:
  do_with_cache:
    parameters:
    ...
    paths:
       type: string-array
    steps:
       ...
       - save_cache:
          key: ...
          paths: << parameters.paths >>
```

What do you think about supporting string-array in parameters?
Moreover, I'd like to know a workaround for this purpose if it exists.
