### ISSUE TITLE
Dependencies between jobs defined in orbs

### ISSUE THREAD

**Issue by paddycarey** [CircleCI-Public/config-preview-sdk#37]
Hi, I've been playing around with the orbs functionality and it's really great, exactly what I need to finally port some code away from our internal CI to Circle, but I've found a small issue in the current implementation.

I know it's just a preview so expect there to be bugs, is this the right place to report issues with the preview? If not let me know and I can report elsewhere.

I've defined the following `config.yml` file:

```yaml
version: 2.1

orbs:
  sk:
    executors:
      default:
        docker:
          - image: circleci/python:3.7.0
    jobs:
      run-tests:
        executor: default
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Test Container
              command: echo "Building test container..."
          - run:
              name: Run Tests
              command: echo "Running tests..."
          - store_test_results:
              path: /tmp/test-results
      build-application:
        executor: default
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Container
              command: echo "Building application..."
      deploy-application:
        executor: default
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Deploy Application
              command: echo "Deploying application..."

workflows:
  main:
    jobs:
      - sk/run-tests
      - sk/build-application
      - sk/deploy-application:
          requires:
            - sk/run-tests
            - sk/build-application
      - hold:
          type: approval
          requires:
            - sk/deploy-application
```

Pushing this results in the following error on the workflow page:

![image](https://user-images.githubusercontent.com/164309/44028217-14646cbe-9ef1-11e8-9b23-28989cc5c7e9.png)

If I remove the `hold` step the workflow runs but appears to misname the `sk/deploy-application` job as just `deploy-application`:

![image](https://user-images.githubusercontent.com/164309/44028287-4a733948-9ef1-11e8-9383-0ad95752f2af.png)

And then it ultimately fails with the following error:

![image](https://user-images.githubusercontent.com/164309/44028332-6d646850-9ef1-11e8-825a-d3b210bdade6.png)

If I give the deploy job an explicit name of `sk/deploy-application` it fails with the same error as before:

```yaml
workflows:
  main:
    jobs:
      - sk/run-tests
      - sk/build-application
      - sk/deploy-application:
          name: sk/deploy-application
          requires:
            - sk/run-tests
            - sk/build-application
      - hold:
          type: approval
          requires:
            - sk/deploy-application
```

![image](https://user-images.githubusercontent.com/164309/44028426-bddd8d66-9ef1-11e8-8da1-92d36d086298.png)

But if I give the job an explicit name _without_ the orb prefix it seems to work fine:

```yaml
workflows:
  main:
    jobs:
      - sk/run-tests
      - sk/build-application
      - sk/deploy-application:
          name: deploy-application
          requires:
            - sk/run-tests
            - sk/build-application
      - hold:
          type: approval
          requires:
            - deploy-application
```

![image](https://user-images.githubusercontent.com/164309/44028527-12497694-9ef2-11e8-84b2-f6c622a79ea4.png)

I'd appreciate any pointers if i'm doing something wrong, or if I can provide any more info to help debug this please do reach out. Thanks!

**Comment by johnswanson** [comment]
Hey @paddycarey! Thanks so much for the bug report, I've been working on orbs for a while and it's super exciting to finally get people using it!

First off, a minor config issue--I *think* you want something like:

```
- sk/run-tests
- sk/build-application
- hold:
    type: approval
    requires:
      - sk/run-tests
      - sk/build-application
  - sk/deploy-application
      requires:
        - hold
```

(So the deployment requires the hold, and the hold job requires the build/test jobs.)

But this still doesn't work :(

The bug here is actually the same one as #38 . Part of our system isn't correctly resolving a "namespaced" job (`foo/bar`) that gets passed arguments (like `requires: ["hold"]`). I'm going to look into this tomorrow!

Thanks again for checking out orbs and providing such a thorough bug report!
