### ISSUE TITLE
Support for array/list/set parameter and maps

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#45]
I would like to make another suggestion for a further feature. For me, it would come very handy if you added support for some kind of array, list or set parameter that can be parsed to a list of steps. Here is an example of how it may look:
```yaml
commands:
  send:
    parameters:
      messages:
        description: "Messages to use"
        type: list #sorted
        items: # like Swagger
          type: string
        default: ["hey", "ho"]
    steps:
    - run: wait for connection
    - map:
        elements: << parameters.messages >>
        steps:
          - run: prepare next message
          - run: send << map.messages >> # use a different prefix group allowing nested maps without conflicts
    - map:
        elements: << parameters.messages >>
        id: msg
        steps:
          - run: prepare saving
          - run: save << map.msg >>
```

This is just an example, but imagine the same for build preparation where you pass a variable number of arguments per build, having a 1:n relation. I could use that for `docker tag << map.tag >>`.
