### ISSUE TITLE
Parameter expansion is not supported in the "executor" field

### ISSUE THREAD

**Issue by ylemkimon** [CircleCI-Public/config-preview-sdk#50]
```yaml
version: 2.1

executors:
  node6:
    docker:
      - image: circleci/node:6
  node8:
    docker:
      - image: circleci/node:8

jobs:
  test:
    parameters:
      exc:
        type: string
    executor: << parameters.exc >>
    steps:
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test:
          exc: node6
      - test:
          exc: node8
```

Using parameter in the `executor` field gives an error: Cannot find a definition for a executor named << parameters.exc >>

**Comment by matfax** [comment]
Alternatively, they could directly allow `executor`s in the workflows.
```yaml
workflows:
  test:
    jobs:
      - test:
          executor: nodeorb/node:6 # assuming we use an orb
      - test:
          # no executor defined -> use job's executor
```
