### ISSUE TITLE
Pass built-in variables to the preprocessing scope

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#52]
This idea is another enhancement I would find useful if or once #15 is implemented, using some of the [builtin variables](https://circleci.com/docs/2.0/env-vars/) as parameters or in conditions:

```yaml
  when:
    condition:
      equals: ["<< builtin.branch >>", "master"]
      steps:
      - run: echo "Something you only do on the master branch"
```

```yaml
  jobs:
    - myorb:
        release-tag: << builtin.tag >>
```

Sure, that can be done already within the shell, but having a schema is more idiomatic and safe.
