### ISSUE TITLE
Naming conflicts not detected

### ISSUE THREAD

**Issue by matfax** [CircleCI-Public/config-preview-sdk#58]
Even if workflow jobs are in separate filters, if you use the same names for them, the preprocessing arbitrarily chooses one of both without an error.
```yaml
version: 2.1
workflows:
  build_master:
    jobs:
    - orb/build_test_push:
        <<: *master_filter
        name: build_something
      use_args: false
  build_pull_request:
    jobs:
    - orb/build_test:
        <<: *pull_request_filter
        some_other_argument: true
        name: build_something
```
From the syntax, it's not clear that conflicts from distinct `workflow` jobs with the same name might occur (i.e., `orb/build_test_push`, and `orb/build_test`) . But during preprocessing, the names are passed to the `jobs` scope and there is no workflow separation. So either there should be a conflict error or a the workflow names could be prefixed to their jobs' names (e.g., `build_master/build_something`).
