### ISSUE TITLE
not allowing custom executor names

### ISSUE THREAD

**Issue by wadadli** [CircleCI-Public/config-preview-sdk#84]
I'm getting this error `"gcloud" is not a supported executor type. The supported executor types are "macos", "machine", "docker"`

```
version: 2.1
executors:
  gcloud:
    docker:
    - image: google/cloud-sdk:latest
jobs:
  gcloud_auth_and_configure_docker:
    docker:
    - image: google/cloud-sdk:latest
    environment:
        NAME: celsus
        TAG: latest
        REPO: gcr.io/
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Authenticate CircleCI service account
        command: |
            echo $SA > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud auth configure-docker --quiet
            docker pull nginx:latest
            #docker build --tag $GCR/$NAME:$CIRCLE_SHA1 .
            #docker tag $REPO/$IMAGE:$CIRCLE_SHA1 $GCR/$IMAGE_NAME:$TAG
            #docker push $REPO/$IMAGE:$TAG
            #docker push $REPO/$IMAGE:$CIRCLE_SHA1
  build_container_image:
      executor: gcloud
      steps:
          - run:
              name: Test if things work as we want em too!
              command: |
                  echo $REPO
                  gcloud auth list
workflows:
  version: 2
  push_to_gcr:
    jobs:
    - gcloud_auth_and_configure_docker
    - build_container_image
```

**Comment by wadadli** [comment]
So that's enabled.

**Comment by wadadli** [comment]
I made some changes 

```
version: 2.1
orbs:
    init:
        executors:
          gcloud:
            docker:
            - image: google/cloud-sdk:latest
jobs:
  gcloud_auth_and_configure_docker:
    docker:
    - image: google/cloud-sdk:latest
    environment:
        NAME: celsus
        TAG: latest
        REPO: gcr.io/infra-b553c506
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Authenticate CircleCI service account
        command: |
            echo $SA > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud auth configure-docker --quiet
            docker pull nginx:latest
            #docker build --tag $GCR/$NAME:$CIRCLE_SHA1 .
            #docker tag $REPO/$IMAGE:$CIRCLE_SHA1 $GCR/$IMAGE_NAME:$TAG
            #docker push $REPO/$IMAGE:$TAG
            #docker push $REPO/$IMAGE:$CIRCLE_SHA1
  build_container_image:
      executor: gcloud
      steps:
          - run:
              name: Test if things work as we want em too!
              command: |
                  echo $REPO
                  gcloud auth list
version: 2.1
workflows:
  push_to_gcr:
    jobs:
    - gcloud_auth_and_configure_docker
    - build_container_image
```
so now the error message is `Error: Cannot find a definition for a executor named gcloud
`

**Comment by yundt** [comment]
The first version looks sufficient - usage of orbs should not be required. I succeeded in running the following stripped-down example with "Enable build processing (preview)" on:

```yaml
version: 2.1
executors:
  gcloud:
    docker:
    - image: google/cloud-sdk:latest
jobs:
  gcloud_auth_and_configure_docker:
    docker:
    - image: google/cloud-sdk:latest
    steps:
    - setup_remote_docker
    - run: echo test
  build_container_image:
      executor: gcloud
      steps:
          - run: echo test
workflows:
  version: 2
  push_to_gcr:
    jobs:
    - gcloud_auth_and_configure_docker
    - build_container_image
```

With "Enable build processing (preview)" off it fails exactly the way you described in your original issue. Could you please try running this example?
