### ISSUE TITLE
experimental notify configuration doesn't work in 2.1

### ISSUE THREAD

**Issue by jfirebaugh** [CircleCI-Public/config-preview-sdk#91]
I have a config.yml with:

```
experimental:
  notify:
    branches:
      only:
        - /release-.*/
        - master
```

However, as soon as I changed `version: 2` to `version: 2.1`, I started getting notifications for every branch. Is this expected? Is there a replacement for this functionality in 2.1?

**Comment by ndintenfass** [comment]
Confirmed bug. We will fix soon.

**Comment by ndintenfass** [comment]
(note that internal CircleCI reference is: CIRCLE-14259)

**Comment by marcomorain** [comment]
I've just confirmed that this is fixed 👌

**Comment by schmijos** [comment]
Has this been "unfixed" lately?

```yml
experimental:
  notify:
    branches:
      only:
        - master
        - develop
```

I get a lot of Slack notifications like this (I'm fiddling around with the CI configuration):

![image](https://user-images.githubusercontent.com/245443/57622406-cfe15380-758d-11e9-8dde-cdcf1a0477f4.png)
